services:
  flask_app:
    image: flask_app:latest
    # image: flask_app:v2
    ports:
      - "5000:5000"
    environment:
      - NODE_API_URL=http://node_api:3000/api/data
      - FLASK_ENV=development
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback         # TO ZATRZYMA I COFNIJE UPDATE PRZY BŁĘDZIE
        monitor: 15s                     # obserwuj nowy kontener przez 15s po uruchomieniu
        max_failure_ratio: 0.1           # pozwól tylko na 10% błędów (np. 1 z 10 kontenerów)
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3

  node_api:
    image: node_api:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
